spring.application.name=ChatBotClient

# OpenAI Config
spring.ai.openai.api-key={API_KEY}
spring.ai.openai.chat.model=gpt-4o
spring.ai.openai.embedding.model=text-embedding-3-small

# PDF file location (put your PDF in src/main/resources)
app.pdf.path=classpath:SpringBoot.pdf


spring.datasource.url= jdbc:postgresql://localhost:5434/postgres
spring.datasource.username= username
spring.datasource.password= password
spring.datasource.driver-class-name= org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
